175. Combine Two Tables

In [1]:
import pandas as pd

In [2]:
# Person table
person = pd.DataFrame({
    'personId': [1, 2],
    'lastName': ['Wang', 'Alice'],
    'firstName': ['Allen', 'Bob']
})

# Address table
address = pd.DataFrame({
    'addressId': [1, 2],
    'personId': [2, 3],
    'city': ['New York City', 'Leetcode'],
    'state': ['New York', 'California']
})

In [48]:
merged = person.merge(address,
                       left_on = 'personId',
                       right_on = 'personId',
                       how = 'left'
                       )

In [49]:
merged

   personId lastName firstName  addressId           city     state
0         1     Wang     Allen        NaN            NaN       NaN
1         2    Alice       Bob        1.0  New York City  New York

In [45]:
person

   personId lastName firstName
0         1     Wang     Allen
1         2    Alice       Bob

In [40]:
address

   addressId  personId           city       state
0          1         2  New York City    New York
1          2         3       Leetcode  California

In [50]:
# answer
merged[['firstName','lastName','city','state']]

  firstName lastName           city     state
0     Allen     Wang            NaN       NaN
1       Bob    Alice  New York City  New York

In [23]:
result = merged[['firstName','lastName','city','state']]
result

  firstName lastName           city       state
0     Allen     Wang  New York City    New York
1       Bob    Alice       Leetcode  California