Write a solution to find the employees who earn more than their managers.
<br>
Return the result table in any order.
<br>
The result format is in the following example.
<br>

In [ ]:
import pandas as pd

In [30]:

df = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"],
    "salary": [70000, 80000, 60000, 90000],
    "managerId": [3, 4, None, None]
})

In [33]:
merged = df.merge(
    df,
    left_on="managerId",
    right_on='id',
    suffixes=("_emp", "_mgr")
)
merged

,id_emp,name_emp,salary_emp,managerId_emp,id_mgr,name_mgr,salary_mgr,managerId_mgr
0,1,Joe,70000,3.0,3,Sam,60000,NaN
1,2,Henry,80000,4.0,4,Max,90000,NaN

In [43]:
re = merged[merged['salary_emp']>merged['salary_mgr']]
re[['name_emp']]

  name_emp
0      Joe

In [ ]:

students = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "dept_id": [101, 102, 101, 103]
})

departments = pd.DataFrame({
    "department_id": [101, 102, 103],
    "department_name": ["Computer Science", "Mechanical", "Civil"]
})


merge = students.merge(
    departments,
    left_on='dept_id',
    right_on='department_id'
)

In [ ]:
merge