183. Customers Who Never Order

In [2]:
import pandas as pd

# Customers table
customers = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Joe', 'Henry', 'Sam', 'Max']
})

# Orders table
orders = pd.DataFrame({
    'id': [1, 2],
    'customerId': [3, 1]
})

In [27]:
merge = customers.merge(orders,left_on = 'id',right_on = 'customerId',how = 'left')
result = merge[merge['customerId'].isnull()][['name']].rename(columns={'name':'Customers'})

In [28]:
result

  Customers
1     Henry
3       Max

   Customers
1        NaN
3        NaN